setwd("/mnt/lustre/home/cusanovich/500HT/dege/")
phcvts = list.files("./",pattern=".ph-cvt")
forder = read.table("../findivs.500ht.ordered.txt")
genes = read.table("../qqnorm.500ht.gccor.newcovcor.genenames.txt")
#expressed = read.table("../qqnorm.500ht.gccor.newcovcor.ordered.bimbam")
#texpressed = t(expressed)
#as = rep('A',times=dim(texpressed)[1])
#ts = rep('T',times=dim(texpressed)[1])
#one = cbind(genes,as)
#two = cbind(one,ts)
#oexp = cbind(two,texpressed)
#write.table(oexp,"expression_gemma_format.txt",row.names=F,col.names=F,quote=F,sep=", ")
for(i in 1:length(phcvts)){
	pheno = read.table(phcvts[i],header=T)
	phenoname = gsub("[.]ph-cvt","",phcvts[i])
	print(phenoname)
	porder = match(forder[,1],pheno[,1])
	write.table(pheno[porder,2],paste0(phenoname,"_phenotype.txt"),row.names=F,col.names=F,quote=F)
	write.table(pheno[porder,3:dim(pheno)[2]],paste0(phenoname,"_covariates.txt"),row.names=F,col.names=F,quote=F)
	system(paste0("~/Programs/gemma0.94 -g expression_gemma_format.txt -p ", phenoname, "_phenotype.txt -k ../addSNP.500ht.ordered.square.txt -c ", phenoname, "_covariates.txt -notsnp -lmm 4 -o ", phenoname))
}
